


<html>
<head>
<title>一卡通网站查询系统</title>
<style type="text/css">
	<!--
		body {
			font-size: 12px;
		}
	-->
	</style>
<script language="JavaScript" type="text/JavaScript">
function doSummit(){

   if (document.FormPost.name.value.length<1 || document.FormPost.passwd.value.length<1){
		alert("登陆号、密码缺一不可!");
		return false;
	}else if((document.FormPost.loginType.options[document.FormPost.loginType.selectedIndex].value==1)&&(!checkinput(document.FormPost.name.value)))
	{ 	   
        alert("您填写的登陆号必须是数字!");
        return false;  
	}else if(document.FormPost.rand.value.length<1){
		alert('对不起！验证码不能为空！');
		return false;
	}else if(document.FormPost.passwd.value.length!=6)
	{
	  alert('对不起!您的密码必须是6位!');
	  return false;
	}else{
	       document.FormPost.action="loginstudent.action";
           return true;
	}
	
	
			  
}

var inputstr;
function checkinput(inputstr)
{
  var reg=/^[0-9]{1,20}$/;
  if( !reg.test(inputstr))
     {
        return false;  
      } else{
        return true;
      }
}
function JAccountSb(){
      location.href="/shjdportalHome.jsp";
}
function doReset(){
	FormPost.reset();
}
</script>
<SCRIPT language="JavaScript">
<!--
function scrollit(seed) {
var m1 = "欢 迎 进 入 本 网 站        ";
var m2 = "建 议 使 用 1024×768 分 辨 率        ";
var m3 = "IE6.0 以 上 版 本 访 问          ";
var m4 = "谢谢您的支持！          ";
var msg=m1+m2+m3+m4;
var out = " ";
var c = 1;
if (seed > 100) {
seed--;
cmd="scrollit("+seed+")";
timerTwo=window.setTimeout(cmd,100);
}
else if (seed <= 100 && seed > 0) {
for (c=0 ; c < seed ; c++) {
out+=" ";
}
out+=msg;
seed--;
window.status=out;
cmd="scrollit("+seed+")";
timerTwo=window.setTimeout(cmd,100);
}
else if (seed <= 0) {
if (-seed < msg.length) {
out+=msg.substring(-seed,msg.length);
seed--;
window.status=out;
cmd="scrollit("+seed+")";
timerTwo=window.setTimeout(cmd,100);
}
else {
window.status=" ";
timerTwo=window.setTimeout("scrollit(100)",75);
}
}
}

function show(a){
	if(a=='C'){
		document.FormPost.passwd.value= "";
	}//else if(a=='B'){
	//	var str = window.pwd.value;
	//	var len = str.length;
	//	window.pwd.value = str.substr(0,len-1);
	//}
	else{
		if(document.FormPost.passwd.value.length==6){
			return;
		}
		document.FormPost.passwd.value += a;
	}
}

function showmap(){
　　document.getElementById("layermap").style.visibility="visible";//显示 
}

function hiddenmap(){
   document.getElementById("layermap").style.visibility="hidden";//隐藏 
}
//-->
</SCRIPT>
<script language=javascript>
// bigin fly bar
var bIsCatchFlyBar = false;
var dragClickX = 0;
var dragClickY = 0;
function catchFlyBar(e){
bIsCatchFlyBar = true;
var x=event.x+document.body.scrollLeft;
var y=event.y+document.body.scrollTop;
dragClickX=x-layermap.style.pixelLeft;
dragClickY=y-layermap.style.pixelTop;
layermap.setCapture();
document.onmousemove = moveFlyBar;
}
function releaseFlyBar(e){
bIsCatchFlyBar = false;
layermap.releaseCapture();
document.onmousemove = null;
}
function moveFlyBar(e){
if(bIsCatchFlyBar){
layermap.style.left = event.x+document.body.scrollLeft-dragClickX;
layermap.style.top = event.y+document.body.scrollTop-dragClickY;
}
}
function myload_flybar(){
layermap.style.top=document.body.scrollTop;
layermap.style.left=document.body.offsetWidth-layermap.clientWidth-30+document.body.scrollLeft;
}

window.onresize = myload_flybar;
window.onscroll = myload_flybar;
// end fly bar
</script>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<meta http-equiv="Pragma" contect="no-cache">
<link href="/css/style1/shouyeziti.css" rel="stylesheet" type="text/css">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_reloadPage(init) {  //reloads the window if Nav4 resized
  if (init==true) with (navigator) {if ((appName=="Netscape")&&(parseInt(appVersion)==4)) {
    document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}
  else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();
}
MM_reloadPage(true);

function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}

function MM_swapImgRestore() { //v3.0
  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_swapImage() { //v3.0
  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)
   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}
}
//-->
</script>
</head>
<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" bgcolor="#FFFFFF" onLoad="scrollit(100);MM_preloadImages('/images/style1/xitun1.jpg','/images/style1/ka2.jpg','/images/style1/fa2.jpg','/images/style1/xun2.jpg','/images/style1/shi2.jpg','/images/style1/pu2.jpg','/images/style1/shang2.jpg','/images/style1/wang2.jpg')">

<form name="FormPost" method="post" onSubmit="return doSummit();">
    <table width="1003" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <th height="10" background="/images/style1/ding1.jpg" scope="col"></th>
      </tr>
    </table>
<div id="layermap" onMouseDown="catchFlyBar()" onMouseUp="releaseFlyBar()" style="position:absolute; left:250px; top:200px; width:203px; height:103px; z-index:1;visibility:hidden"">
 <img src="getpasswdPhoto.action" width="150" height="190" border="0" usemap="#Map"/>
  <map name="Map" id="Map"> 
                      <area shape="rect" coords="4,31,44,69" onclick="javascript:show('0')" />
		              <area shape="rect" coords="54,33,94,71" onclick="javascript:show('1');" ondblClick="javascript:show('1');"/>
		              <area shape="rect" coords="99,33,141,71" onclick="javascript:show('2');" ondblClick="javascript:show('2');" />
		
		              <area shape="rect" coords="5,74,46,106" onclick="javascript:show('3');" ondblClick="javascript:show('3');" />
		              <area shape="rect" coords="54,75,95,106" onclick="javascript:show('4');" ondblClick="javascript:show('4');" />
		              <area shape="rect" coords="101,75,141,107" onclick="javascript:show('5');" ondblClick="javascript:show('5');"" />
		
		              <area shape="rect" coords="6,112,47,143" onclick="javascript:show('6');" ondblClick="javascript:show('6');" />
		              <area shape="rect" coords="54,113,93,143" onclick="javascript:show('7');" ondblClick="javascript:show('7');" />
		              <area shape="rect" coords="102,113,142,143" onclick="javascript:show('8');" ondblClick="javascript:show('8');" />
		
		              <area shape="rect" coords="6,150,46,182" onclick="javascript:show('9');" ondblClick="javascript:show('9');" />
		              <area shape="rect" coords="54,151,94,183" onclick="javascript:show('C');" ondblClick="javascript:show('C');" />
		              <area shape="rect" coords="101,151,142,183" onclick="javascript:hiddenmap();"  />
		</map>
</div>
<table width="800" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr>
          <td width="800"><table width="800" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td><table width="800" height="25" border="0" cellpadding="0" cellspacing="0">
                  <tr>
                    <td>


<html>
<head>
<title></title>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<link href="/css/shouyeziti.css" rel="stylesheet" type="text/css">
</head>
<body bgcolor="#FFFFFF" text="#000000" valign="top" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
	<table width="800" height="25" border="0" cellpadding="0" cellspacing="0">
		<tr>
			<th width="79" height="21" class="shouyeziti" scope="col"><div align="center"><a href="homeLogin.action">首 页</a></div></th>
			<th width="8" align="center" valign="middle" scope="col"><div align="center"><img src="/images/style1/wenshudao.jpg" width="3" height="21"></div></th>
			        
				<th width="79" class="shouyeziti" scope="col"><div align="center">
					<a href='xxsearch.action?lmid=4af8bf44187768c5011887d04fa20003'>业务办理</a></div>
				</th>
				<th width="8" scope="col"><div align="center"><img src="/images/style1/wenshudao.jpg" width="3" height="21"></div></th>
			        
				<th width="79" class="shouyeziti" scope="col"><div align="center">
					<a href='xxsearch.action?lmid=4af8bf44187768c5011887d19c460004'>使用指南</a></div>
				</th>
				<th width="8" scope="col"><div align="center"><img src="/images/style1/wenshudao.jpg" width="3" height="21"></div></th>
			        
				<th width="79" class="shouyeziti" scope="col"><div align="center">
					<a href='xxsearch.action?lmid=4af8bf44187768c5011887cdcbd70001'>新闻动态</a></div>
				</th>
				<th width="8" scope="col"><div align="center"><img src="/images/style1/wenshudao.jpg" width="3" height="21"></div></th>
			        
				<th width="79" class="shouyeziti" scope="col"><div align="center">
					<a href='xxsearch.action?lmid=4af8bf44187768c5011887d226940005'>规章制度</a></div>
				</th>
				<th width="8" scope="col"><div align="center"><img src="/images/style1/wenshudao.jpg" width="3" height="21"></div></th>
			        
				<th width="79" class="shouyeziti" scope="col"><div align="center">
					<a href='xxsearch.action?lmid=4af8bf4428bd9e150128d394b6d20001'>相关链接</a></div>
				</th>
				<th width="8" scope="col"><div align="center"><img src="/images/style1/wenshudao.jpg" width="3" height="21"></div></th>
			
			
			<th width="60" height="21" class="shouyeziti" scope="col"><div align="center"><a href="#" onClick="i=window.showModalDialog('/application/sel_style.htm',window,'dialogWidth:460px;dialogHeight:320px;status:no;s croll:no;help:no;');if(i == 1) self.location.reload();">风格设置</a></div></th>
			<th width="8" align="center" valign="middle" scope="col"><div align="center"><img src="/images/style1/wenshudao.jpg" width="3" height="21"></div></th>
		</tr>
	</table>
 </body>
</html></td>
                    
                   </tr>
               <tr>
                <td></td>
              </tr>
          </table></td>
        </tr>
        <tr>
          <td height="104" class="flashbian"><img src="/imagesschool/style1/flash2.jpg" width="800" height="128"></td>
        </tr>
      </table>
      <table width="800"  border="0" cellpadding="0" cellspacing="0">
        <tr> 
          <th width="177" height="188" align="left" valign="middle" scope="col"> 
            <table width="172" height="136" border="0" align="right" cellpadding="0" cellspacing="0">
              <tr> 
                <th height="2" colspan="4" valign="top" scope="col"></th>
              </tr>
              <tr> 
                <th height="12" colspan="4" valign="top" scope="col" width="173" height="24" background="/imagesschool/style1/chikaren.jpg" scope="col"><a href="/shjdportalHome.jsp"><img border="0" name="imageField1" style="CURSOR: hand" src="/imagesschool/style1/jaccount.gif"></a></th>
              </tr>
              <tr> 
                <th width="8" height="110" valign="top" background="/images/style1/kuangtiao.jpg" scope="col"> 
                  <p></p>
                </th>
                <th width="157" height="110" align="left" valign="top" background="/images/style1/kuangtiao.jpg" scope="col"> 
                  
				  
                    <table width="155" height="110" border="0" align="right" cellpadding="0" cellspacing="0">
                      <tr> 
                        <th width="60" scope="col"> 
                          <div align="center"><span class="denglu">帐号</span></div>
                        </th>
                        <th width="89" scope="col"> 
                          <div align="left"><span class="kuangziti"> 
                            <input name="name" type="text" class="kuangziti" size="12" style="background-color:#FFFFFF" onfocus="style.backgroundColor='#999999'" onblur="style.backgroundColor='#FFFFFF'">
                            </span></div>
                        </th>
                      </tr>
                      <tr> 
                        <input type="hidden" name="userType" value="1">
                        <th scope="col"> 
                          <div align="center"><span class="denglu">查询密码</span></div>
                        </th>
                        <th scope="col"> 
                          <div align="left"><span class="kuangziti"> 
                           
                           
                            <input name="passwd" type="password"  maxlength="6" class="kuangziti" size="12" onfocus="style.backgroundColor='#999999';" style="background-color:#FFFFFF" onblur="style.backgroundColor='#FFFFFF'">
                          
                            </span></div>
                        </th>
                      </tr>
                      <tr> 
                        <th scope="col"> 
                          <div align="center"><span class="denglu">用户类型</span></div>
                        </th>
                        <th scope="col"> 
                          <div align="left"><span class="kuangziti"> 
                            <select name="loginType" class ="and">
                               
                              <option value="2">学(工)号登录</option>
                               
                              <option value="1">帐号登录</option>
                               
                            </select>
                            </span></div>
                        </th>
                      </tr>
                      <tr> 
                        <th scope="col"> 
                          <div align="center"><span class="denglu">验证码</span></div>
                        </th>
                        <th scope="col"> 
                          <div align="left"><span class="kuangziti"> 
                            <input name="rand" maxlength=4 size="4" style="background-color:#FFFFFF" onfocus="style.backgroundColor='#999999'" onblur="style.backgroundColor='#FFFFFF'">
                            <script language="javascript">document.write("<img valign=middle border=0 src='getCheckpic.action?rand="+Math.random()*10000+"'>");</script>
                            </span></div>
                        </th>
                      </tr>       
                    </table>               
				     
                    <div align="center" class="huizi"> </div>
                  </th>
                <th width="8" valign="top" background="/images/style1/kuangtiao.jpg" scope="col"></th>
              </tr>
              <tr background="/images/style1/kuangdi.jpg"> 
                <th height="34" colspan="4" align="center" valign="middle" background="/images/style1/kuangdi.jpg" scope="col"><input type="image" style="CURSOR: hand" border="0" name="imageField" src="/images/style1/denglu.jpg">&nbsp;&nbsp;&nbsp;<img src="/images/style1/chongxie.jpg" width="52" height="22"  onClick="doReset()"  style="CURSOR: hand" border="0"></th>
              </tr>

            </table>
          </th>
          <th width="444" align="left" valign="top" scope="col" height="432" rowspan="2">
            <table  height="190" border="0" cellpadding="0" cellspacing="0">
              <tr> 
                <th width="1" rowspan="15" align="left" valign="top" scope="col">&nbsp;</th>
                <th height="5" colspan="4" align="left" valign="top" scope="col"></th>
                <th width="1" rowspan="15" align="left" valign="top" scope="col"></th>
              </tr>
              <tr> 
                <th height colspan="3" align="left" valign="top" background="" scope="col"> 
                  <table width="426" height="33" border="0" cellpadding="0" cellspacing="0">
                    <tr> 
                      <th width="9" height="36" scope="col"><img src="/images/style1/rrrr-3.jpg" width="9" height="35"></th>
                      <th width="32" background="/images/style1/rrrr-1.jpg" scope="col" height="36"><img src="/images/style1/rrrr-2.jpg" width="7" height="12"></th>
                      <th width="358" align="left" valign="middle" background="/images/style1/rrrr-1.jpg" class="zuixing" scope="col" height="36"><div align="right"></div>                        业务办理</th>
                      <th width="10" height="36" scope="col"><img src="/images/style1/rrrr-4.jpg" width="9" height="35"></th>
                    </tr>
                  </table>         
                  <table width="100%" border="0">
                      
                  <tr>
                    <th align="left" valign="middle"  class="lan" scope="col"><img src="/images/rrrr-5.jpg" width="6" height="11">2015/09/30  │<a style="CURSOR: hand" onClick="window.open('managerOneGgxxfb.action?fbxxid=8ae482954fba437a01501bc071400001','university','height=370,width=700,fullscreen=no,location=no,scrollbars=yes,status=yes,menubar=no,left=0,top=0,resizable=yes')" >2015“十一”期间校园卡中心对外服务时间安排</a></th>
                  </tr>       
                  <tr>
                    <th align="center" valign="middle" scope="col"><img src="/images/style1/rrrr-6.jpg" width="425" height="3"></th>
                  </tr>
               
                  <tr>
                    <th align="left" valign="middle"  class="lan" scope="col"><img src="/images/rrrr-5.jpg" width="6" height="11">2014/10/22  │<a style="CURSOR: hand" onClick="window.open('managerOneGgxxfb.action?fbxxid=4af8bf441c45f2e2011c463bbfac0003','university','height=370,width=700,fullscreen=no,location=no,scrollbars=yes,status=yes,menubar=no,left=0,top=0,resizable=yes')" >一卡通申领表(卢湾校区专用)</a></th>
                  </tr>       
                  <tr>
                    <th align="center" valign="middle" scope="col"><img src="/images/style1/rrrr-6.jpg" width="425" height="3"></th>
                  </tr>
               
                  <tr>
                    <th align="left" valign="middle"  class="lan" scope="col"><img src="/images/rrrr-5.jpg" width="6" height="11">2014/09/25  │<a style="CURSOR: hand" onClick="window.open('managerOneGgxxfb.action?fbxxid=8ae4829548abf42e0148ac02d42b0001','university','height=370,width=700,fullscreen=no,location=no,scrollbars=yes,status=yes,menubar=no,left=0,top=0,resizable=yes')" >【通告】现已开通支付宝为校园卡充值服务</a></th>
                  </tr>       
                  <tr>
                    <th align="center" valign="middle" scope="col"><img src="/images/style1/rrrr-6.jpg" width="425" height="3"></th>
                  </tr>
               
                  <tr>
                    <th align="left" valign="middle"  class="lan" scope="col"><img src="/images/rrrr-5.jpg" width="6" height="11">2014/06/09  │<a style="CURSOR: hand" onClick="window.open('managerOneGgxxfb.action?fbxxid=4af8bf44187768c50118880fd4e20014','university','height=370,width=700,fullscreen=no,location=no,scrollbars=yes,status=yes,menubar=no,left=0,top=0,resizable=yes')" >校园卡中心对外服务时间</a></th>
                  </tr>       
                  <tr>
                    <th align="center" valign="middle" scope="col"><img src="/images/style1/rrrr-6.jpg" width="425" height="3"></th>
                  </tr>
               
                  <tr>
                    <th align="left" valign="middle"  class="lan" scope="col"><img src="/images/rrrr-5.jpg" width="6" height="11">2014/04/14  │<a style="CURSOR: hand" onClick="window.open('managerOneGgxxfb.action?fbxxid=4af8bf44187768c50118881359540017','university','height=370,width=700,fullscreen=no,location=no,scrollbars=yes,status=yes,menubar=no,left=0,top=0,resizable=yes')" >校园卡现金充值点服务时间</a></th>
                  </tr>       
                  <tr>
                    <th align="center" valign="middle" scope="col"><img src="/images/style1/rrrr-6.jpg" width="425" height="3"></th>
                  </tr>
              
                  </table>
                </th>
              </tr> 
              <tr> 
                <th height="11" colspan="3" align="right" valign="middle" scope="col"><a   href='ggxxfb.action?lmid=4af8bf44187768c5011887d04fa20003' ><img src="/images/rrrr-7.jpg"   border="0"></a></th>
              </tr> 
            </table>
            <table width="418" height="225" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <th width="1" rowspan="14" align="left" valign="top" scope="col">&nbsp;</th>
                <th height="30" colspan="3" align="left" valign="top" background="" scope="col"> 
                  <table width="426" height="33" border="0" cellpadding="0" cellspacing="0" >
                    <tr> 
                      <th width="9" height="36" scope="col"><img src="/images/style1/rrrr-3.jpg" width="9" height="35"></th>
                      <th width="32" background="/images/style1/rrrr-1.jpg" scope="col" height="36"><img src="/images/style1/rrrr-2.jpg" width="7" height="12"></th>
                      <th width="358" align="left" valign="middle" background="/images/style1/rrrr-1.jpg" class="zuixing" scope="col" height="36">使用指南</th>
                      <th width="10" height="36" scope="col"><img src="/images/style1/rrrr-4.jpg" width="9" height="35"></th>
                    </tr>
                  </table>
                   <table width="100%" border="0">
                      
             <tr>
                    <th align="left" valign="middle"  class="lan" scope="col"><img src="images/rrrr-5.jpg" width="6" height="11">2014/05/12  │<a style="CURSOR: hand" onClick="window.open('managerOneGgxxfb.action?fbxxid=4af8bf441a326e76011a3812972b0001','university','height=370,width=700,fullscreen=no,location=no,scrollbars=yes,status=yes,menubar=no,left=0,top=0,resizable=yes')" >校园一卡通使用手册</a></th>
                  </tr>       
                  <tr>
                    <th height="2" align="center" valign="middle" scope="col"><img src="/images/style1/rrrr-6.jpg" width="425" height="3"></th>
                  </tr>
               
             <tr>
                    <th align="left" valign="middle"  class="lan" scope="col"><img src="images/rrrr-5.jpg" width="6" height="11">2014/05/12  │<a style="CURSOR: hand" onClick="window.open('managerOneGgxxfb.action?fbxxid=4af8bf44187768c50118881884bf0019','university','height=370,width=700,fullscreen=no,location=no,scrollbars=yes,status=yes,menubar=no,left=0,top=0,resizable=yes')" >圈存机转账不收手续费</a></th>
                  </tr>       
                  <tr>
                    <th height="2" align="center" valign="middle" scope="col"><img src="/images/style1/rrrr-6.jpg" width="425" height="3"></th>
                  </tr>
               
             <tr>
                    <th align="left" valign="middle"  class="lan" scope="col"><img src="images/rrrr-5.jpg" width="6" height="11">2014/05/12  │<a style="CURSOR: hand" onClick="window.open('managerOneGgxxfb.action?fbxxid=4af8bf44187768c50118881e1a3e001a','university','height=370,width=700,fullscreen=no,location=no,scrollbars=yes,status=yes,menubar=no,left=0,top=0,resizable=yes')" >浴室及公寓控水器使用说明</a></th>
                  </tr>       
                  <tr>
                    <th height="2" align="center" valign="middle" scope="col"><img src="/images/style1/rrrr-6.jpg" width="425" height="3"></th>
                  </tr>
               
             <tr>
                    <th align="left" valign="middle"  class="lan" scope="col"><img src="images/rrrr-5.jpg" width="6" height="11">2014/05/12  │<a style="CURSOR: hand" onClick="window.open('managerOneGgxxfb.action?fbxxid=4af8bf44187768c50118883033d1001f','university','height=370,width=700,fullscreen=no,location=no,scrollbars=yes,status=yes,menubar=no,left=0,top=0,resizable=yes')" >如何补办校园卡</a></th>
                  </tr>       
                  <tr>
                    <th height="2" align="center" valign="middle" scope="col"><img src="/images/style1/rrrr-6.jpg" width="425" height="3"></th>
                  </tr>
               
             <tr>
                    <th align="left" valign="middle"  class="lan" scope="col"><img src="images/rrrr-5.jpg" width="6" height="11">2014/05/12  │<a style="CURSOR: hand" onClick="window.open('managerOneGgxxfb.action?fbxxid=4af8bf44187768c50118883306970021','university','height=370,width=700,fullscreen=no,location=no,scrollbars=yes,status=yes,menubar=no,left=0,top=0,resizable=yes')" >校园卡如何解挂？</a></th>
                  </tr>       
                  <tr>
                    <th height="2" align="center" valign="middle" scope="col"><img src="/images/style1/rrrr-6.jpg" width="425" height="3"></th>
                  </tr>
               
             <tr>
                    <th align="left" valign="middle"  class="lan" scope="col"><img src="images/rrrr-5.jpg" width="6" height="11">2014/05/12  │<a style="CURSOR: hand" onClick="window.open('managerOneGgxxfb.action?fbxxid=4af8bf44187768c50118883525500022','university','height=370,width=700,fullscreen=no,location=no,scrollbars=yes,status=yes,menubar=no,left=0,top=0,resizable=yes')" >校园卡可否转让给他人使用？</a></th>
                  </tr>       
                  <tr>
                    <th height="2" align="center" valign="middle" scope="col"><img src="/images/style1/rrrr-6.jpg" width="425" height="3"></th>
                  </tr>
               
             <tr>
                    <th align="left" valign="middle"  class="lan" scope="col"><img src="images/rrrr-5.jpg" width="6" height="11">2014/05/12  │<a style="CURSOR: hand" onClick="window.open('managerOneGgxxfb.action?fbxxid=4af8bf44187768c5011888365e0e0023','university','height=370,width=700,fullscreen=no,location=no,scrollbars=yes,status=yes,menubar=no,left=0,top=0,resizable=yes')" >校园卡内应该存多少钱？</a></th>
                  </tr>       
                  <tr>
                    <th height="2" align="center" valign="middle" scope="col"><img src="/images/style1/rrrr-6.jpg" width="425" height="3"></th>
                  </tr>
               
             <tr>
                    <th align="left" valign="middle"  class="lan" scope="col"><img src="images/rrrr-5.jpg" width="6" height="11">2014/05/12  │<a style="CURSOR: hand" onClick="window.open('managerOneGgxxfb.action?fbxxid=4af8bf44187768c50118883ad2ea0025','university','height=370,width=700,fullscreen=no,location=no,scrollbars=yes,status=yes,menubar=no,left=0,top=0,resizable=yes')" >如何通过自助设备为校园卡充值？</a></th>
                  </tr>       
                  <tr>
                    <th height="2" align="center" valign="middle" scope="col"><img src="/images/style1/rrrr-6.jpg" width="425" height="3"></th>
                  </tr>
              
                  </table>
                </th>
                <th width="1" rowspan="14" align="left" valign="top" scope="col"></th>
              </tr>        
              <tr> 
                <th height="11" colspan="3" align="right" valign="middle" scope="col"><a  href='ggxxfb.action?lmid=4af8bf44187768c5011887d19c460004' ><img src="/images/rrrr-7.jpg" width="50" height="15"  border="0"></a></th>
              </tr>
            </table>
          </th>
          <th width="193" align="right" valign="top" scope="col" rowspan="2"> 
            <table width="193" border="0" cellpadding="0" cellspacing="0">
              <tr> 
                <th height="411" align="left" valign="top" scope="col">
                  <table width="183" height="407" border="0" cellpadding="0" cellspacing="0">
                    <tr> 
                      <th height="39" align="left" valign="top" scope="col"> 
                        <table width="179" height="176" border="0" cellpadding="0" cellspacing="0">
                          <tr> 
                            <th width="182" height="38" align="center" valign="bottom" class="baibian" scope="col"><img src="/images/style1/xunka.jpg" width="193" height="39"></th>
                          </tr>
                          <tr> 
                            <th height="98" align="left" valign="top" background="/images/style1/xianxian.jpg" class="huizi" scope="col" width="182"> 
                              <table width="183" height="138" border="0" cellpadding="0" cellspacing="0">
                                <tr> 
                                  <th width="21" height="97" scope="col">&nbsp;</th>
                                  <th width="144" class="huizi" scope="col"> 
                                    <table width="100%" border="0">
                                      <tr> 
                                        <td width="48%"> 
                                          <div align="center"><span class="huizi">帐号</span></div>
                                        </td>
                                        <td width="52%"> 
                                          <div align="center"><span class="huizi">姓名</span></div>
                                        </td>
                                      </tr>
                                    </table>
                                    <marquee behavior=loop direction=up id=news scrollamount=1 scrolldelay=80 onmouseover=this.stop() onmouseout=this.start() 
      style="FONT-WEIGHT: normal; HEIGHT: 100px; LEFT: 0px; MARGIN-LEFT: 1px; TEXT-ALIGN: left; TOP: 1px; WIDTH: 140px"
      background=""><br>
                                    <table width="100%" border="0">
                                       
                                      <tr> 
                                        <td width="59%"> 
                                          <div align="center"><span class="huizi">123457</span></div>
                                        </td>
                                        <td width="41%"> 
                                          <div align="center"><span class="huizi">臧新实</span></div>
                                        </td>
                                      </tr>
                                       
                                      <tr> 
                                        <td width="59%"> 
                                          <div align="center"><span class="huizi">265758</span></div>
                                        </td>
                                        <td width="41%"> 
                                          <div align="center"><span class="huizi">耿飞菲</span></div>
                                        </td>
                                      </tr>
                                       
                                      <tr> 
                                        <td width="59%"> 
                                          <div align="center"><span class="huizi">253799</span></div>
                                        </td>
                                        <td width="41%"> 
                                          <div align="center"><span class="huizi">汪小佳</span></div>
                                        </td>
                                      </tr>
                                       
                                      <tr> 
                                        <td width="59%"> 
                                          <div align="center"><span class="huizi">264509</span></div>
                                        </td>
                                        <td width="41%"> 
                                          <div align="center"><span class="huizi">周梦蝶</span></div>
                                        </td>
                                      </tr>
                                       
                                      <tr> 
                                        <td width="59%"> 
                                          <div align="center"><span class="huizi">56683</span></div>
                                        </td>
                                        <td width="41%"> 
                                          <div align="center"><span class="huizi">蔡海燕</span></div>
                                        </td>
                                      </tr>
                                       
                                      <tr> 
                                        <td width="59%"> 
                                          <div align="center"><span class="huizi">266041</span></div>
                                        </td>
                                        <td width="41%"> 
                                          <div align="center"><span class="huizi">高子昂</span></div>
                                        </td>
                                      </tr>
                                       
                                      <tr> 
                                        <td width="59%"> 
                                          <div align="center"><span class="huizi">175397</span></div>
                                        </td>
                                        <td width="41%"> 
                                          <div align="center"><span class="huizi">苏慧慧</span></div>
                                        </td>
                                      </tr>
                                       
                                      <tr> 
                                        <td width="59%"> 
                                          <div align="center"><span class="huizi">264399</span></div>
                                        </td>
                                        <td width="41%"> 
                                          <div align="center"><span class="huizi">冯世祥</span></div>
                                        </td>
                                      </tr>
                                       
                                    </table>
                                  </th>
                                  <th width="18" scope="col">&nbsp;</th>
                                </tr>
                              </table>
                            </th>
                          </tr>
                          <tr> 
                            <th height="6" align="center" valign="top" scope="col" width="182"><img src="/images/style1/kkd.jpg" width="193" height="9"></th>
                          </tr>
                        </table>
                        <div align="center"><img src="/images/style1/shika.jpg" width="193" height="39"></div>
                      </th>
                    </tr>
                    <tr> 
                      <th height="66" align="left" valign="top" background="/images/style1/xianxian.jpg" scope="col">
                        <table width="183" height="82" border="0" cellpadding="0" cellspacing="0">
                          <tr> 
                            <th width="18" height="67" scope="col">&nbsp;</th>
                            <th width="146" scope="col"> 
                              <table width="100%" border="0">
                                <tr> 
                                  <td width="48%"> 
                                    <div align="center"><span class="huizi">帐号</span></div>
                                  </td>
                                  <td width="52%"> 
                                    <div align="center"><span class="huizi">姓名</span></div>
                                  </td>
                                </tr>
                              </table>
                              <marquee behavior=loop direction=up id=news scrollamount=1 scrolldelay=80 onmouseover=this.stop() onmouseout=this.start() 
      style="FONT-WEIGHT: normal; HEIGHT: 60px; LEFT: 0px; MARGIN-LEFT: 1px; TEXT-ALIGN: left; TOP: 1px; WIDTH: 140px"
      background=""><br>
                              <table width="100%" border="0">
                                 
                                <tr> 
                                  <td width="59%"> 
                                    <div align="center"><span class="huizi">117333</span></div>
                                  </td>
                                  <td width="41%"> 
                                    <div align="center"><span class="huizi">黄?华</span></div>
                                  </td>
                                </tr>
                                 
                                <tr> 
                                  <td width="59%"> 
                                    <div align="center"><span class="huizi">148575</span></div>
                                  </td>
                                  <td width="41%"> 
                                    <div align="center"><span class="huizi">杨光</span></div>
                                  </td>
                                </tr>
                                 
                                <tr> 
                                  <td width="59%"> 
                                    <div align="center"><span class="huizi">13925</span></div>
                                  </td>
                                  <td width="41%"> 
                                    <div align="center"><span class="huizi">刘畅</span></div>
                                  </td>
                                </tr>
                                 
                                <tr> 
                                  <td width="59%"> 
                                    <div align="center"><span class="huizi">65573</span></div>
                                  </td>
                                  <td width="41%"> 
                                    <div align="center"><span class="huizi">郑斌</span></div>
                                  </td>
                                </tr>
                                 
                                <tr> 
                                  <td width="59%"> 
                                    <div align="center"><span class="huizi">26851</span></div>
                                  </td>
                                  <td width="41%"> 
                                    <div align="center"><span class="huizi">沈金伟</span></div>
                                  </td>
                                </tr>
                                 
                                <tr> 
                                  <td width="59%"> 
                                    <div align="center"><span class="huizi">24882</span></div>
                                  </td>
                                  <td width="41%"> 
                                    <div align="center"><span class="huizi">何照照</span></div>
                                  </td>
                                </tr>
                                 
                                <tr> 
                                  <td width="59%"> 
                                    <div align="center"><span class="huizi">26005</span></div>
                                  </td>
                                  <td width="41%"> 
                                    <div align="center"><span class="huizi">郭祥</span></div>
                                  </td>
                                </tr>
                                 
                                <tr> 
                                  <td width="59%"> 
                                    <div align="center"><span class="huizi">26070</span></div>
                                  </td>
                                  <td width="41%"> 
                                    <div align="center"><span class="huizi">宁仁松</span></div>
                                  </td>
                                </tr>
                                 
                                <tr> 
                                  <td width="59%"> 
                                    <div align="center"><span class="huizi">35454</span></div>
                                  </td>
                                  <td width="41%"> 
                                    <div align="center"><span class="huizi">任重远</span></div>
                                  </td>
                                </tr>
                                 
                                <tr> 
                                  <td width="59%"> 
                                    <div align="center"><span class="huizi">38290</span></div>
                                  </td>
                                  <td width="41%"> 
                                    <div align="center"><span class="huizi">张大群</span></div>
                                  </td>
                                </tr>
                                 
                              </table>
                            </th>
                            <th width="19" scope="col">&nbsp;</th>
                          </tr>
                        </table>
                      </th>
                    </tr>
                    <tr> 
                      <th height="9" align="center" valign="top" scope="col"><img src="/images/style1/kkd.jpg" width="193" height="9"></th>
                    </tr>
                    <tr> 
                      <th height="103" align="left" valign="top" scope="col">
                        <table width="191" height="111" border="0" cellpadding="0" cellspacing="0">
                          <tr> 
                            <th width="192" height="39" scope="col"><img src="/images/style1/zaixian.jpg" width="193" height="39"></th>
                          </tr>
                          <tr> 
                            <th height="63" align="left" valign="top" background="/images/style1/xianxian.jpg" scope="col">
                              <table width="183" height="55" border="0" cellpadding="0" cellspacing="0">
                                <tr> 
                                  <th width="14" height="55" scope="col">&nbsp;</th>
                                  <th width="149" scope="col"><span class="huizi"> 
                                    <marquee behavior=loop direction=up id=news scrollamount=1 scrolldelay=80 onmouseover=this.stop() onmouseout=this.start() 
      style="FONT-WEIGHT: normal; HEIGHT: 60px; LEFT: 0px; MARGIN-LEFT: 1px; TEXT-ALIGN: left; TOP: 1px; WIDTH: 140px"
      background=""><br>
                                     
                                    <div align="left"><span class="huizi"><a href="showquestion.action" target="_blank">&nbsp;&nbsp;您是否赞成由学校统一办理中国银行借记卡并与校园卡关联自助转账？</a></span></div>
                                     </span></th>
                                  <th width="20" scope="col">&nbsp;</th>
                                </tr>
                              </table>
                            </th>
                          </tr>
                          <tr> 
                            <th height="9" scope="col"><img src="/images/style1/kkd.jpg" width="193" height="9"></th>
                          </tr>
                        </table>
                      </th>
                    </tr>
                  </table>
                </th>
              </tr>
            </table>
          </th>
        </tr>
        <tr>
          <th width="177" height="216" align="left" valign="top" scope="col">
            <table width="170" height="241" border="0" align="right" cellpadding="0" cellspacing="0">
              <tr> 
                <th height="27" align="left" valign="top" scope="col"> 
                  <div align="right"><img src="/images/style1/wangshangyewu.jpg" width="173" height="27"></div>
                </th>
              </tr>
              <tr> 
                <th height="26" align="center" valign="middle" scope="col"> 
                  <div align="center"><a href="homeXtzc.action" onMouseOver="MM_swapImage('Image1','','/images/style1/xitun1.jpg',1)" onMouseOut="MM_swapImgRestore()"><img src="/images/style1/xitun.jpg" name="Image1" width="173" height="26" border="0" id="Image1"></a></div>
                </th>
              </tr>
              <tr> 
                <th height="2" align="left" valign="top" background="/images/style1/gang1.jpg" scope="col"><img src="/images/style1/heng1.jpg" width="169" height="2"></th>
              </tr>
              <tr> 
                <th height="26" align="center" valign="middle" scope="col"> 
                  <div align="left"><a href="homeKpgn.action" onMouseOver="MM_swapImage('Image2','','/images/style1/ka2.jpg',1)" onMouseOut="MM_swapImgRestore()"><img src="/images/style1/ka1.jpg" name="Image2" width="173" height="26" border="0" id="Image2"></a></div>
                </th>
              </tr>
              <tr> 
                <th height="2" align="center" valign="middle" background="/images/style1/gang2.jpg" scope="col"><img src="/images/style1/heng2.jpg" width="173" height="2"></th>
              </tr>
              <tr> 
                <th height="26" align="center" valign="middle" scope="col"> 
                  <div align="left"><a href="homeKfdw.action" onMouseOver="MM_swapImage('Image3','','/images/style1/fa2.jpg',1)" onMouseOut="MM_swapImgRestore()"><img src="/images/style1/fa1.jpg" name="Image3" width="173" height="26" border="0" id="Image3"></a></div>
                </th>
              </tr>
              <tr> 
                <th align="left" valign="top" background="/images/style1/gang3.jpg" scope="col"><img src="/images/style1/heng3.jpg" width="166" height="2"></th>
              </tr>
              <tr> 
                <th height="26" align="center" valign="middle" scope="col"> 
                  <div align="left"><a href="accountlossList.action" onMouseOver="MM_swapImage('Image4','','/images/style1/xun2.jpg',1)" onMouseOut="MM_swapImgRestore()"><img src="/images/style1/xun1.jpg" name="Image4" width="173" height="26" border="0" id="Image4"></a></div>
                </th>
              </tr>
              <tr> 
                <th height="4" align="left" valign="top" background="/images/style1/gang4.jpg" scope="col"><img src="/images/style1/heng4.jpg" width="169" height="4"></th>
              </tr>
              <tr> 
                <th height="26" align="center" valign="middle" scope="col"> 
                  <div align="left"><a href="nFixcardAllList.action" onMouseOver="MM_swapImage('Image5','','/images/style1/shi2.jpg',1);MM_swapImage('Image5','','/images/style1/shi2.jpg',1)" onMouseOut="MM_swapImgRestore()"><img src="/images/style1/shi1.jpg" name="Image5" width="173" height="26" border="0" id="Image5"></a></div>
                </th>
              </tr>
              <tr> 
                <th height="3" align="left" valign="top" background="/images/style1/gang5.jpg" scope="col"><img src="/images/style1/heng5.jpg" width="166" height="3"></th>
              </tr>
              <tr> 
                <th height="26" align="center" valign="middle" scope="col"> 
                  <div align="left"><a href="indexmercLogin.action" onMouseOver="MM_swapImage('Image6','','/images/style1/pu2.jpg',1);MM_swapImage('Image6','','/images/style1/pu2.jpg',1)" onMouseOut="MM_swapImgRestore()"><img src="/images/style1/pu1.jpg" name="Image6" width="173" height="26" border="0" id="Image6"></a></div>
                </th>
              </tr>
              <tr> 
                <th height="4" align="left" valign="top" background="/images/style1/gang6.jpg" scope="col"><img src="/images/style1/heng6.jpg" width="169" height="4"></th>
              </tr>
              <tr> 
                <th height="26" align="center" valign="middle" scope="col"> 
                  <div align="left"><a href="indexleaderLogin.action" onMouseOver="MM_swapImage('Image7','','/images/style1/shang2.jpg',1)" onMouseOut="MM_swapImgRestore()"><img src="/images/style1/shang1.jpg" name="Image7" width="173" height="26" border="0" id="Image7"></a></div>
                </th>
              </tr>
              <tr> 
                <th align="left" valign="top" background="/images/style1/gang7.jpg" scope="col"><img src="/images/style1/heng7.jpg" width="169" height="2"></th>
              </tr>
              <th height="26" align="center" valign="middle" scope="col"> 
                <div align="left"><a href="indexmanagerLogin.action" onMouseOver="MM_swapImage('Image8','','/images/style1/wang2.jpg',1)" onMouseOut="MM_swapImgRestore()"><img src="/images/style1/wang1.jpg" name="Image8" width="173" height="26" border="0" id="Image8"></a></div>
              </th>
              <tr> 
            </table>
          </th>
        </tr>
        



<html>
<head>
<title></title>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">

<link href="/css/shouyeziti.css" rel="stylesheet" type="text/css">

</head>
<body bgcolor="#FFFFFF" text="#000000" valign="top" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
    <table width="800" border="0" cellpadding="0" cellspacing="0">
    <tr align="center" valign="middle" >
          <th height="53" width="65%"  colspan="3" background="/images/style1/dibu0.jpg" scope="col"><div align="right" class="haha">版权所有:哈尔滨新中新电子股份有限公司 版本号:2.6.0.0<!-- 初始化counter这个Bean,实例为useBean --> 
<br>
        (C)Copyright 2003,Harbin synjones electronic co.,ltd</div></th>
        <th height="53" width="35%"  align="right" colspan="3" background="/images/style1/dibu0.jpg" scope="col"><div class="haha">
       您是第<img width=8pt height=15pt src='/images/style1/2.gif'><img width=8pt height=15pt src='/images/style1/6.gif'><img width=8pt height=15pt src='/images/style1/4.gif'><img width=8pt height=15pt src='/images/style1/2.gif'>位访问者

         &nbsp; </div></th>
      </tr>
    </table>
</body>
</html> 
      </table>
</table>
</form>
</body>
</html>